---
title: "EGFR_mutant_response_rates"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#dataset 1
library(readr)
nsclc_pd1_msk_2018 <- read_delim("~/Yossi/nsclc_pd1_msk_2018_clinical_data.tsv",
"\t", escape_double = FALSE, trim_ws = TRUE)
data_mutations_extended <- read_delim("~/Yossi/nsclc_pd1_msk_2018/data_mutations_extended.txt",
"\t", escape_double = FALSE, trim_ws = TRUE)
EGFR_muts <- data_mutations_extended[data_mutations_extended$Hugo_Symbol == "EGFR",]

EGFR_In_Frame_Del <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Del"])
EGFR_In_Frame_Ins <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Ins"])
EGFR_L858R <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$HGVSp_Short == "p.L858R"])
EGFR_other <- unique(EGFR_muts$Tumor_Sample_Barcode[!(EGFR_muts$HGVSp_Short %in% c("p.L858R","p.E746_A750del","p.S752_I759del","p.L747_A750delinsP","p.S768_D770dup","p.P772_H773dup","p.D770_N771insY","p.H773dup"))])
nsclc_pd1_msk_2018$EGFR_In_Frame_Del <- c("no","yes")[as.numeric(sapply(nsclc_pd1_msk_2018$`Sample ID`, function(x) x %in% EGFR_In_Frame_Del)) + 1]
nsclc_pd1_msk_2018$EGFR_In_Frame_Ins <- c("no","yes")[as.numeric(sapply(nsclc_pd1_msk_2018$`Sample ID`, function(x) x %in% EGFR_In_Frame_Ins)) + 1]
nsclc_pd1_msk_2018$EGFR_L858R <- c("no","yes")[as.numeric(sapply(nsclc_pd1_msk_2018$`Sample ID`, function(x) x %in% EGFR_L858R)) + 1]
nsclc_pd1_msk_2018$EGFR_other <- c("no","yes")[as.numeric(sapply(nsclc_pd1_msk_2018$`Sample ID`, function(x) x %in% EGFR_other)) + 1]
EGFR_status <- rep("WT", nrow(nsclc_pd1_msk_2018))
EGFR_status[nsclc_pd1_msk_2018$EGFR_other == "yes"] = "other"
EGFR_status[nsclc_pd1_msk_2018$EGFR_L858R == "yes"] = "L858R"
EGFR_status[nsclc_pd1_msk_2018$EGFR_In_Frame_Ins == "yes"] = "In_Frame_Ins"
EGFR_status[nsclc_pd1_msk_2018$EGFR_In_Frame_Del == "yes"] = "In_Frame_Del"
nsclc_pd1_msk_2018$EGFR_status = EGFR_status


d1 <- data.frame(response = as.numeric(nsclc_pd1_msk_2018$`Durable Clinical Benefit`[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"] == "YES"), EGFR = c("MUT","WT")[as.numeric(nsclc_pd1_msk_2018$EGFR_status[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"] == "WT")+1], TMB = scale(nsclc_pd1_msk_2018$`Mutation Rate`[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"]), EGFR_status = nsclc_pd1_msk_2018$EGFR_status[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"], treatment_type = nsclc_pd1_msk_2018$`Treatment Type`[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"])
rownames(d1) <- nsclc_pd1_msk_2018$`Sample ID`[nsclc_pd1_msk_2018$`Durable Clinical Benefit` != "NE"]

```



```{r}
#dataset 2
library(readxl)
data_mutations_extended <- read_excel("~/Yossi/43018_2019_8_MOESM2_ESM.xlsx",sheet = "S3", skip = 1)
nsclc_2020 <- read_excel("~/Yossi/43018_2019_8_MOESM2_ESM.xlsx",sheet = "S1", skip = 1)
nsclc_2020 <- nsclc_2020[1:89,]
TMB_data <- read_excel("~/Yossi/43018_2019_8_MOESM8_ESM.xlsx",sheet = "ED1")
nsclc_2020$TMB = TMB_data$TMB
nsclc_2020$cTMB = TMB_data$cTMB
EGFR_muts <- data_mutations_extended[data_mutations_extended$Gene == "EGFR",]
EGFR_In_Frame_Del <- unique(EGFR_muts$`Patient ID`[EGFR_muts$`Mutation Type` == "Deletion"])
EGFR_In_Frame_Ins <- unique(EGFR_muts$`Patient ID`[EGFR_muts$`Mutation Type` == "Insertion"])
EGFR_L858R <- unique(EGFR_muts$`Patient ID`[EGFR_muts$`Amino Acid (protein)` == "858L>R"])
EGFR_other <- unique(EGFR_muts$`Patient ID`[EGFR_muts$`Mutation Type` == "Substitution" & EGFR_muts$`Amino Acid (protein)` != "858L>R"])

nsclc_2020$EGFR_In_Frame_Del <- c("no","yes")[as.numeric(sapply(nsclc_2020$`Patient ID`, function(x) x %in% EGFR_In_Frame_Del)) + 1]
nsclc_2020$EGFR_In_Frame_Ins <- c("no","yes")[as.numeric(sapply(nsclc_2020$`Patient ID`, function(x) x %in% EGFR_In_Frame_Ins)) + 1]
nsclc_2020$EGFR_L858R <- c("no","yes")[as.numeric(sapply(nsclc_2020$`Patient ID`, function(x) x %in% EGFR_L858R)) + 1]
nsclc_2020$EGFR_other <- c("no","yes")[as.numeric(sapply(nsclc_2020$`Patient ID`, function(x) x %in% EGFR_other)) + 1]


EGFR_status <- rep("WT", nrow(nsclc_2020))
EGFR_status[nsclc_2020$EGFR_other == "yes"] = "other"
EGFR_status[nsclc_2020$EGFR_L858R == "yes"] = "L858R"
EGFR_status[nsclc_2020$EGFR_In_Frame_Ins == "yes"] = "In_Frame_Ins"
EGFR_status[nsclc_2020$EGFR_In_Frame_Del == "yes"] = "In_Frame_Del"
nsclc_2020$EGFR_status = EGFR_status

nsclc_2020 <- nsclc_2020[nsclc_2020$`Clinical Benefit` != "N/A",]

d2 <- data.frame(response = as.numeric(nsclc_2020$`Clinical Benefit` == "DCB"), EGFR = c("MUT","WT")[as.numeric(nsclc_2020$EGFR_status == "WT")+1], TMB = scale(nsclc_2020$TMB), EGFR_status = nsclc_2020$EGFR_status, treatment_type = nsclc_2020$Treatment)

rownames(d2) <- nsclc_2020$`Patient ID`
```



```{r}
#dataset 3:
mskcc_2018 <- read_delim("~/Yossi/nsclc_mskcc_2018_clinical_data.tsv", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

data_mutations_extended <- read_delim("~/Yossi/nsclc_mskcc_2018/data_mutations_extended.txt","\t", escape_double = FALSE, trim_ws = TRUE)

EGFR_muts <- data_mutations_extended[data_mutations_extended$Hugo_Symbol == "EGFR",]

EGFR_In_Frame_Del <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Del"])
EGFR_In_Frame_Ins <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Ins"])
EGFR_L858R <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$HGVSp_Short == "p.L858R"])
EGFR_other <- unique(EGFR_muts$Tumor_Sample_Barcode[!(EGFR_muts$Variant_Classification %in% c("In_Frame_Ins","In_Frame_Del") | EGFR_muts$HGVSp_Short == "p.L858R")])

mskcc_2018$EGFR_In_Frame_Del <- c("no","yes")[as.numeric(sapply(mskcc_2018$`Sample ID`, function(x) x %in% EGFR_In_Frame_Del)) + 1]
mskcc_2018$EGFR_In_Frame_Ins <- c("no","yes")[as.numeric(sapply(mskcc_2018$`Sample ID`, function(x) x %in% EGFR_In_Frame_Ins)) + 1]
mskcc_2018$EGFR_L858R <- c("no","yes")[as.numeric(sapply(mskcc_2018$`Sample ID`, function(x) x %in% EGFR_L858R)) + 1]
mskcc_2018$EGFR_other <- c("no","yes")[as.numeric(sapply(mskcc_2018$`Sample ID`, function(x) x %in% EGFR_other)) + 1]
EGFR_status <- rep("WT", nrow(mskcc_2018))
EGFR_status[mskcc_2018$EGFR_other == "yes"] = "other"
EGFR_status[mskcc_2018$EGFR_L858R == "yes"] = "L858R"
EGFR_status[mskcc_2018$EGFR_In_Frame_Ins == "yes"] = "In_Frame_Ins"
EGFR_status[mskcc_2018$EGFR_In_Frame_Del == "yes"] = "In_Frame_Del"
mskcc_2018$EGFR_status = EGFR_status

d3 <- data.frame(response = as.numeric(mskcc_2018$`Durable Clinical Benefit` == "Durable Clinical Benefit"), EGFR = c("MUT","WT")[as.numeric(mskcc_2018$EGFR_status == "WT")+1], TMB = scale(mskcc_2018$`Nonsynonymous Mutation Burden`), EGFR_status = mskcc_2018$EGFR_status, treatment_type = rep("anti-PD1 + anti-CTLA4", nrow(mskcc_2018)))

rownames(d3) <- mskcc_2018$`Sample ID`
```




```{r}
#dataset4
mskcc_2015 <- read_delim("~/Yossi/nsclc_mskcc_2015_clinical_data.tsv", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

data_mutations_extended <- read_delim("~/Yossi/nsclc_mskcc_2015/data_mutations_extended.txt","\t", escape_double = FALSE, trim_ws = TRUE)

EGFR_muts <- data_mutations_extended[data_mutations_extended$Hugo_Symbol == "EGFR",]

EGFR_In_Frame_Del <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Del"])
EGFR_In_Frame_Ins <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Ins"])
EGFR_L858R <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$HGVSp_Short == "p.L858R"])
EGFR_other <- unique(EGFR_muts$Tumor_Sample_Barcode[!(EGFR_muts$Variant_Classification %in% c("In_Frame_Ins","In_Frame_Del") | EGFR_muts$HGVSp_Short == "p.L858R")])

mskcc_2015$EGFR_In_Frame_Del <- c("no","yes")[as.numeric(sapply(mskcc_2015$`Sample ID`, function(x) x %in% EGFR_In_Frame_Del)) + 1]
mskcc_2015$EGFR_In_Frame_Ins <- c("no","yes")[as.numeric(sapply(mskcc_2015$`Sample ID`, function(x) x %in% EGFR_In_Frame_Ins)) + 1]
mskcc_2015$EGFR_L858R <- c("no","yes")[as.numeric(sapply(mskcc_2015$`Sample ID`, function(x) x %in% EGFR_L858R)) + 1]
mskcc_2015$EGFR_other <- c("no","yes")[as.numeric(sapply(mskcc_2015$`Sample ID`, function(x) x %in% EGFR_other)) + 1]
EGFR_status <- rep("WT", nrow(mskcc_2015))
EGFR_status[mskcc_2015$EGFR_other == "yes"] = "other"
EGFR_status[mskcc_2015$EGFR_L858R == "yes"] = "L858R"
EGFR_status[mskcc_2015$EGFR_In_Frame_Ins == "yes"] = "In_Frame_Ins"
EGFR_status[mskcc_2015$EGFR_In_Frame_Del == "yes"] = "In_Frame_Del"
mskcc_2015$EGFR_status = EGFR_status


d4 <- data.frame(response = as.numeric(mskcc_2015$`Durable Clinical Benefit` == "DCB"), EGFR = c("MUT","WT")[as.numeric(mskcc_2015$EGFR_status == "WT")+1], TMB = scale(mskcc_2015$`Nonsynonymous mutation burden`), EGFR_status = mskcc_2015$EGFR_status, treatment_type = rep("anti-PD1(pembrolizumab)",nrow(mskcc_2015)))

rownames(d4) <- mskcc_2015$`Sample ID`
```

```{r}
hastings2019_EGFRWT <- read_excel("~/Yossi/mdz141-suppl_data/Summary of characteristics of EGFR WT patients treated with immune checkpoint inhibitors.xlsx")

hastings2019_EGFRWT$response <- sapply(1:nrow(hastings2019_EGFRWT), function(i) {
  if(hastings2019_EGFRWT$`Best Overall Response`[i] %in% c("PR","CR"))
    return("Durable Clinical Benefit")
  else if(hastings2019_EGFRWT$`Best Overall Response`[i] == "SD" & hastings2019_EGFRWT$`PFS (mo)`[i] > 6)
    return("Durable Clinical Benefit")
  else
    return("No Durable Benefit")
})
hastings2019_EGFR_Mut <- read_excel("~/Yossi/mdz141-suppl_data/Summary of patient characteristics for EGFR mutant patients treated with immune checkpoint inhibitors.xlsx")
hastings2019_EGFR_Mut$response <- sapply(1:nrow(hastings2019_EGFR_Mut), function(i) {
  if(hastings2019_EGFR_Mut$`Best Response`[i] %in% c("PR","CR"))
    return("Durable Clinical Benefit")
  else if(hastings2019_EGFR_Mut$`Best Response`[i] == "SD" & hastings2019_EGFR_Mut$`PFS (mo)`[i] > 6)
    return("Durable Clinical Benefit")
  else
    return("No Durable Benefit")
})
hastings2019_TMB <- read_excel("~/Yossi/mdz141-suppl_data/Summary of characteristics of patients included in the tumor mutation burden analysis.xlsx")
hastings2019_TMB$`Non-synonymous Mutations/Mb` <- scale(hastings2019_TMB$`Non-synonymous Mutations/Mb`)
hastings2019_EGFRWT$TMB = sapply(hastings2019_EGFRWT$STUDY_ID, function(x) {
  idx = which(hastings2019_TMB$`Sample ID` == x)
  if(length(idx) == 1)
    return(hastings2019_TMB$`Non-synonymous Mutations/Mb`[idx])
  else
    return(NA)
})

hastings2019_EGFR_Mut$TMB = sapply(hastings2019_EGFR_Mut$`Study ID`, function(x) {
  idx = which(hastings2019_TMB$`Sample ID` == x)
  if(length(idx) == 1)
    return(hastings2019_TMB$`Non-synonymous Mutations/Mb`[idx])
  else
    return(NA)
})

hastings2019 <- data.frame(EGFR_status = c(rep("WT", nrow(hastings2019_EGFRWT)), hastings2019_EGFR_Mut$`EGFR Mutation`), TMB = c(hastings2019_EGFRWT$TMB, hastings2019_EGFR_Mut$TMB), response = c(hastings2019_EGFRWT$response, hastings2019_EGFR_Mut$response), treatment_type = c(rep("NA", nrow(hastings2019_EGFRWT)),hastings2019_EGFR_Mut$`Immune Target`))

rownames(hastings2019) <- c(hastings2019_EGFRWT$STUDY_ID, hastings2019_EGFR_Mut$`Study ID`)
hastings2019$EGFR_status <- as.character(hastings2019$EGFR_status)
hastings2019$response <- as.numeric(hastings2019$response == "Durable Clinical Benefit")
hastings2019$EGFR_status[hastings2019$EGFR_status == "Del19"] = "In_Frame_Del"
hastings2019$EGFR_status[hastings2019$EGFR_status == "20ins"] = "In_Frame_Ins"
hastings2019$EGFR_status[hastings2019$EGFR_status %in% c("L861Q","G719","Other")] = "other"
hastings2019$EGFR <- c("MUT","WT")[as.numeric(hastings2019$EGFR_status == "WT")+1]
hastings2019 <- hastings2019[,colnames(d4)]
hastings2019$treatment_type <- as.character(hastings2019$treatment_type)
```


```{r}
DD <- rbind(rbind(d1,d2),rbind(d3,d4))
DD <- rbind(DD, hastings2019[!(rownames(hastings2019) %in% rownames(DD)),])
```

```{r}
idx_combo <- DD$treatment_type %in% c("Combination","Dual ICB (anti-PD1+anti-CTLA4)","Anti-PD1 + Chemotherapy","anti-PD1 + anti-CTLA4","CTLA-4 + PD-1","CTLA-4 + PD-L1")

```


```{r}
library(lmtest)
D1 <- DD
D1$EGFR <- c("MUT","WT")[as.numeric(DD$EGFR_status %in% c("WT"))+1]
m <- lm(response ~ EGFR + TMB, data = D1[!idx_combo,])

print(summary(m))
```



```{r}
library(lmtest)
m1 <- lm(response ~ TMB, data = DD[idx_combo,])
m2 <- lm(response ~ TMB + EGFR, data = DD[idx_combo,])
print(lrtest(m1,m2))
print(summary(m2))
```



```{r}
library(dplyr)
library(ggplot2)
summary_dat <- DD %>% group_by(EGFR_status,response) %>% tally()
summary_dat$response <- c("No Durable Benefit","Durable Clinical Benefit")[summary_dat$response+1]
p1 <- ggplot(summary_dat, aes(fill=response, y=n, x=EGFR_status)) + scale_x_discrete(limits = c("WT","L858R","In_Frame_Del","In_Frame_Ins","other")) +
    geom_bar(position="fill", stat="identity") + ylab("ORR") + xlab("EGFR status")
print(p1)
pdf("~/Yossi/Figure1A_all.pdf")
print(p1)
dev.off()
tiff("~/Yossi/Figure1A_all.tiff")
print(p1)
dev.off()
print(summary_dat)
```


```{r}
library(dplyr)
library(ggplot2)
summary_dat <- DD[!idx_combo,] %>% group_by(EGFR_status,response) %>% tally()
summary_dat$response <- c("No Durable Benefit","Durable Clinical Benefit")[summary_dat$response+1]
p1 <- ggplot(summary_dat, aes(fill=response, y=n, x=EGFR_status)) + scale_x_discrete(limits = c("WT","L858R","In_Frame_Del","In_Frame_Ins","other")) + 
    geom_bar(position="fill", stat="identity") + ylab("ORR") + xlab("EGFR status")
print(p1)
pdf("~/Yossi/Figure1A_PD1_PDL1_only.pdf")
print(p1)
dev.off()

tiff("~/Yossi/Figure1A_PD1_PDL1_only.tiff")
print(p1)
dev.off()
print(summary_dat)
```

```{r}
library(dplyr)
library(ggplot2)
summary_dat <- DD[idx_combo,] %>% group_by(EGFR_status,response) %>% tally()
summary_dat$response <- c("No Durable Benefit","Durable Clinical Benefit")[summary_dat$response+1]
p1 <- ggplot(summary_dat, aes(fill=response, y=n, x=EGFR_status)) + scale_x_discrete(limits = c("WT","L858R","In_Frame_Del","In_Frame_Ins","other")) + 
    geom_bar(position="fill", stat="identity") + ylab("ORR") + xlab("EGFR status")
print(p1)
pdf("~/Yossi/Figure1A_PD1_CTLA4.pdf")
print(p1)
dev.off()

tiff("~/Yossi/Figure1A_PD1_CTLA4.tiff")
print(p1)
dev.off()

print(summary_dat)
```



```{r}
DD2 <- DD
DD2$response <- c("No Durable Benefit","Durable Clinical Benefit")[DD$response+1]
write.table(DD2, file = "~/Yossi/Table_for_Fig1A.txt", sep = "\t", row.names = F, quote = F)
```


```{r}
#read in corresponding TCGA clinical data
tcga_clinical <- suppressWarnings(read_excel("~/forKun/TCGA/TCGA-CDR-SupplementalTableS1.xlsx"))
```

```{r}
panTCGA_muts <- read_delim("~/Yossi/mc3.v0.2.8.PUBLIC.maf",
"\t", escape_double = FALSE, trim_ws = TRUE)

```

```{r}

patient_ids <- substr(panTCGA_muts$Tumor_Sample_Barcode,1,12)
is_nsclc <- patient_ids %in% tcga_clinical$bcr_patient_barcode[tcga_clinical$type %in% c("LUAD","LUSC")]
EGFR_muts <- panTCGA_muts[is_nsclc & panTCGA_muts$Hugo_Symbol == "EGFR",]
NSCLC_muts <- panTCGA_muts[is_nsclc,]
TMB <- sapply(unique(NSCLC_muts$Tumor_Sample_Barcode), function(x) {
  idx = NSCLC_muts$Tumor_Sample_Barcode == x
  return(sum(NSCLC_muts$Variant_Classification[idx] != "Silent"))
})


EGFR_In_Frame_Del <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Del"])
EGFR_In_Frame_Ins <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$Variant_Classification == "In_Frame_Ins"])
EGFR_L858R <- unique(EGFR_muts$Tumor_Sample_Barcode[EGFR_muts$HGVSp_Short == "p.L858R"])
EGFR_other <- unique(EGFR_muts$Tumor_Sample_Barcode[!(EGFR_muts$Variant_Classification %in% c("In_Frame_Ins","In_Frame_Del") | EGFR_muts$HGVSp_Short == "p.L858R")])

tcga_nsclc <- data.frame(Sample_ID = names(TMB), TMB = TMB)
tcga_nsclc$EGFR_In_Frame_Del <- c("no","yes")[as.numeric(sapply(tcga_nsclc$Sample_ID, function(x) x %in% EGFR_In_Frame_Del)) + 1]
tcga_nsclc$EGFR_In_Frame_Ins <- c("no","yes")[as.numeric(sapply(tcga_nsclc$Sample_ID, function(x) x %in% EGFR_In_Frame_Ins)) + 1]
tcga_nsclc$EGFR_L858R <- c("no","yes")[as.numeric(sapply(tcga_nsclc$Sample_ID, function(x) x %in% EGFR_L858R)) + 1]
tcga_nsclc$EGFR_other <- c("no","yes")[as.numeric(sapply(tcga_nsclc$Sample_ID, function(x) x %in% EGFR_other)) + 1]
EGFR_status <- rep("WT", nrow(tcga_nsclc))
EGFR_status[tcga_nsclc$EGFR_other == "yes"] = "other"
EGFR_status[tcga_nsclc$EGFR_L858R == "yes"] = "L858R"
EGFR_status[tcga_nsclc$EGFR_In_Frame_Ins == "yes"] = "In_Frame_Ins"
EGFR_status[tcga_nsclc$EGFR_In_Frame_Del == "yes"] = "In_Frame_Del"
tcga_nsclc$EGFR_status = EGFR_status
tcga_nsclc$Sample_ID <- substr(tcga_nsclc$Sample_ID, 1, 12)

nsclc_all <- data.frame(EGFR_status = c(as.character(DD$EGFR_status), as.character(tcga_nsclc$EGFR_status)), TMB = c(DD$TMB,scale(tcga_nsclc$TMB)), response = c(DD2$response, rep(NA, nrow(tcga_nsclc))))
```

```{r}
library(ggpubr)
p2 <- ggplot(data = nsclc_all[!is.na(nsclc_all$TMB),], aes(x = EGFR_status, y = TMB)) + geom_boxplot() + ylab("TMB (normalized)") + xlab("EGFR status") + stat_compare_means() + scale_x_discrete(limits = c("WT","L858R","In_Frame_Del","In_Frame_Ins","other"))
print(p2)

pdf("~/Yossi/Figure1B.pdf")
print(p2)
dev.off()

tiff("~/Yossi/Figure1B.tiff")
print(p2)
dev.off()

print(table(nsclc_all$EGFR_status))

```

```{r}
#tcga_luad_tpm <- readRDS("~/forKun/TCGA/lung_NSCLC_adenocarcinoma_exp_deconv/bulk.rds")
#tcga_lusc_tpm <- readRDS("~/forKun/TCGA/lung_NSCLC_squamous_cell_carcinoma_exp_deconv/bulk.rds")
#tcga_nsclc_tpm <- cbind(tcga_luad_tpm,tcga_lusc_tpm)
#colnames(tcga_nsclc_tpm) <- substr(colnames(tcga_nsclc_tpm),1,12)
```


```{r}
#idx_PD1_resistant <- sapply(colnames(tcga_nsclc_tpm), function(x) x %in% tcga_nsclc$Sample_ID[tcga_nsclc$EGFR_status %in% c("In_Frame_Ins","L858R")])
#all <- sapply(colnames(tcga_nsclc_tpm), function(x) x %in% tcga_nsclc$Sample_ID[tcga_nsclc$EGFR_status %in% c("In_Frame_Ins","L858R","In_Frame_Del")])
```

```{r}
#library(limma)
#design_mat <- as.matrix(data.frame(NR = 1, ResistantvsNonresistant = as.numeric(idx_PD1_resistant[all])))
#fit <- lmFit(log2(tcga_nsclc_tpm[,all]+1), design = design_mat)
#fit <- eBayes(fit)
#de <- topTable(fit, coef="ResistantvsNonresistant", adjust="BH",number = nrow(tcga_nsclc_tpm))
#View(de)
```

```{r}
#final_set <- de[(de$logFC > log2(1.2) | de$logFC < -log2(1.2)) & de$adj.P.Val < 0.05,]

#write.table(final_set, file = "~/Yossi/DE_EGFR_common_mutants_vs_rest.tsv",sep = "\t", quote = F)
```

```{r}
#library(msigdbr)
#library(fgsea)
#gsea <- list()
#m_df <- msigdbr(species = "Homo sapiens", category = "C5")
#m_list <- m_df %>% split(x = .$gene_symbol, f = .$gs_name)

#ranking <- seq(nrow(final_set))
#names(ranking) <- rownames(final_set)[order(final_set$logFC, decreasing = T)]
#load("~/Single Cell/forKun/kegg.pathway.gsets.RData")


#fgseaRes_C2CP <- fgsea(m_list, ranking, nperm = 10000, maxSize = 50, minSize = 15)
#fgseaRes_C2CP <- fgseaRes_C2CP[order(fgseaRes_C2CP$padj),]
```

